// Render an emoji as an OpenMoji SVG (consistent across platforms, crisp, stylable) with a
// graceful fallback to the native glyph. Drop-in for the `<span className="text-Nxl">{emoji}</span>`
// sites: pass the same className — the SVG sizes to 1em, so existing text-size classes keep working,
// and the fallback renders the native char in the same span (identical layout).
//   <Emoji char={world.emoji} className="text-2xl" />
// SVGs are served from /openmoji/<codepoint>.svg (generated by scripts/gen-emoji-assets.mjs).
import { useState } from 'react';
import { emojiToCodepoints } from './emojiCodepoints.js';

export default function Emoji({ char, className = '', title, alt }) {
  const cp = emojiToCodepoints(char);
  const [failed, setFailed] = useState(false);
  const label = alt ?? title ?? char;
  return (
    <span className={className} role="img" aria-label={label}>
      {cp && !failed ? (
        <img
          src={`/openmoji/${cp}.svg`}
          alt=""
          aria-hidden="true"
          draggable={false}
          style={{ width: '1em', height: '1em', display: 'inline-block', verticalAlign: '-0.125em' }}
          onError={() => setFailed(true)}
        />
      ) : (
        char
      )}
    </span>
  );
}
