// Phonics — English Quest World 1. The first audio-first topic, built first
// (per the spec) to flush out the prompt/input extensions the runtime needs.
//
// Per-subject contract (same as the math generators):
//   topic = { id, title, boardKind, bands, generate(band) → problem }
//   problem = { kind, ...board fields, steps: [ step ] }
//   step extends the math step shape with three OPTIONAL, additive fields so
//   the shared quest-runtime needs no English-specific branching:
//     - audioPrompt : clip key for a SOUND prompt (no text)  → e.g. 'phon-b'
//     - inputKind   : 'choice' | 'letterTiles' | 'wordTiles' (default numeric)
//     - choices     : the options to render for choice/tile inputs
// Math problems simply never set these, so math behavior is unchanged.

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const shuffle = (arr) => {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
};

const C = { teal: '#22D3EE', amber: '#FFB953', green: '#4ADE80', purple: '#A78BFA' };

// Single-letter phonemes, in synthetic-phonics teaching order (s,a,t,p,i,n …).
// `key` is the SOUND clip (/voice/<voice>/phon-<x>.mp3, generated by gen-voice);
// `word` is the example word (its own clip 'word-<w>' reinforces on a correct
// answer). Digraphs (sh, ch, th, ck) come in a later band.
export const PHONEMES = [
  { letter: 's', key: 'phon-s', sound: '/s/', word: 'sun' },
  { letter: 'a', key: 'phon-a', sound: '/a/', word: 'ant' },
  { letter: 't', key: 'phon-t', sound: '/t/', word: 'top' },
  { letter: 'p', key: 'phon-p', sound: '/p/', word: 'pig' },
  { letter: 'i', key: 'phon-i', sound: '/i/', word: 'igloo' },
  { letter: 'n', key: 'phon-n', sound: '/n/', word: 'net' },
  { letter: 'm', key: 'phon-m', sound: '/m/', word: 'map' },
  { letter: 'd', key: 'phon-d', sound: '/d/', word: 'dog' },
  { letter: 'g', key: 'phon-g', sound: '/g/', word: 'goat' },
  { letter: 'o', key: 'phon-o', sound: '/o/', word: 'octopus' },
  { letter: 'c', key: 'phon-c', sound: '/k/', word: 'cat' },
  { letter: 'k', key: 'phon-k', sound: '/k/', word: 'kite' },
  { letter: 'e', key: 'phon-e', sound: '/e/', word: 'egg' },
  { letter: 'u', key: 'phon-u', sound: '/u/', word: 'umbrella' },
  { letter: 'r', key: 'phon-r', sound: '/r/', word: 'rat' },
  { letter: 'h', key: 'phon-h', sound: '/h/', word: 'hat' },
  { letter: 'b', key: 'phon-b', sound: '/b/', word: 'ball' },
  { letter: 'f', key: 'phon-f', sound: '/f/', word: 'fish' },
  { letter: 'l', key: 'phon-l', sound: '/l/', word: 'leg' },
  // the rest of the alphabet (taught later; complete the A–Z sound board)
  { letter: 'j', key: 'phon-j', sound: '/j/', word: 'jet' },
  { letter: 'q', key: 'phon-q', sound: '/kw/', word: 'queen' },
  { letter: 'v', key: 'phon-v', sound: '/v/', word: 'van' },
  { letter: 'w', key: 'phon-w', sound: '/w/', word: 'web' },
  { letter: 'x', key: 'phon-x', sound: '/ks/', word: 'box' },
  { letter: 'y', key: 'phon-y', sound: '/y/', word: 'yoyo' },
  { letter: 'z', key: 'phon-z', sound: '/z/', word: 'zebra' },
];

const BY_LETTER = Object.fromEntries(PHONEMES.map((p) => [p.letter, p]));

// word → picture, so a correct answer can SHOW what was said (e.g. "fish" → 🐟).
// Words without a clean emoji simply show as text (the board falls back gracefully).
export const WORD_EMOJI = {
  sun: '☀️', ant: '🐜', top: '🔝', pig: '🐷', igloo: '🧊', net: '🥅', map: '🗺️', dog: '🐶',
  goat: '🐐', octopus: '🐙', cat: '🐱', kite: '🪁', egg: '🥚', umbrella: '☂️', rat: '🐀',
  hat: '🎩', ball: '⚽', fish: '🐟', leg: '🦵', pin: '📌', pan: '🍳', can: '🥫', bed: '🛏️',
  bus: '🚌', cup: '☕', hen: '🐔', run: '🏃', fan: '🪭', bug: '🐛', mop: '🧹', pop: '🎈',
  bun: '🥯', man: '🧑', mat: '🧶', dig: '⛏️', fun: '🎉', hop: '🐰', ship: '🚢', chip: '🍟',
  thumb: '👍', duck: '🦆', jet: '✈️', queen: '👑', van: '🚐', web: '🕸️', box: '📦',
  yoyo: '🪀', zebra: '🦓',
};

// Bands = how much of the alphabet is in play (gentle progression).
const BANDS = [
  ['s', 'a', 't', 'p', 'i', 'n'], // band 0 — classic first set
  ['s', 'a', 't', 'p', 'i', 'n', 'm', 'd', 'g', 'o', 'c', 'k'], // band 1
  PHONEMES.map((p) => p.letter), // band 2 — all single letters
];

export function bandLetters(band) {
  return BANDS[Math.max(0, Math.min(BANDS.length - 1, band))];
}

// Sound → Letter: play a phoneme, child taps the matching letter.
export function genSoundToLetter(band = 0) {
  const letters = bandLetters(band);
  const target = BY_LETTER[pick(letters)];
  const pool = letters.filter((l) => l !== target.letter);
  const distractors = shuffle(pool).slice(0, Math.min(3, pool.length));
  const choices = shuffle([target.letter, ...distractors]);

  return {
    kind: 'soundToLetter',
    letter: target.letter,
    word: target.word,
    result: target.letter,
    steps: [
      {
        focus: [],
        targets: ['ans-0'],
        effects: [],
        preEffects: [],
        chip: { label: 'Letter Sounds', color: C.teal },
        banner: 'Listen — which letter makes this sound?',
        prompt: 'Tap the letter you hear',
        audioPrompt: target.key, // the SOUND is the prompt (no readable text)
        inputKind: 'choice',
        choices,
        lower: band >= 2, // uppercase first; lowercase introduced at band 2 (All Letter Sounds)
        expected: target.letter,
        hint: `It says ${target.sound}, like in "${target.word}". That's the letter ${target.letter.toUpperCase()}!`,
        sayQ: ['q-whichletter', target.key], // "which letter says…" + the sound
        sayA: [`word-${target.word}`], // reinforce with the example word
      },
    ],
  };
}

// The topic, honoring the per-subject contract.
export const letterSounds = {
  id: 'letter-sounds',
  title: 'Letter Sounds',
  boardKind: 'soundToLetter',
  bands: [0, 1, 2],
  generate: genSoundToLetter,
};

// ── Blending (CVC) ──────────────────────────────────────────────────────────
// Decodable consonant-vowel-consonant words, real + spellable from each band's
// letters. The prompt plays the word's SOUNDS (segmented), the child builds the
// spelling from scrambled letter tiles. Audio-first, no picture needed.
const BLEND_BANDS = [
  ['sat', 'sit', 'tip', 'tin', 'pin', 'pit', 'nap', 'pan', 'tap', 'sip'],
  ['sat', 'tip', 'pin', 'pan', 'cat', 'dog', 'mat', 'map', 'dig', 'dot', 'cop', 'top', 'pig', 'can'],
  ['cat', 'dog', 'pig', 'bed', 'bus', 'cup', 'hat', 'hen', 'leg', 'run', 'fan', 'bug', 'net', 'sun'],
];
// every distinct blend word (for gen-voice word-<w> clips + smoke)
export const BLEND_WORDS = [...new Set(BLEND_BANDS.flat())];

export function genBlend(band = 0) {
  const words = BLEND_BANDS[Math.max(0, Math.min(BLEND_BANDS.length - 1, band))];
  const word = pick(words);
  const letters = word.split('');
  return {
    kind: 'blendWord',
    word,
    result: word,
    steps: [
      {
        focus: [],
        targets: ['ans-0'],
        effects: [],
        preEffects: [],
        chip: { label: 'Blending', color: C.green },
        banner: 'Listen to the sounds — then build the word!',
        prompt: 'Tap the letters in order',
        audioPrompt: `word-${word}`, // the blended word (single-clip contract)
        sounds: letters.map((l) => `phon-${l}`), // segmented sounds for "play the sounds"
        inputKind: 'build',
        tiles: shuffle(letters),
        lower: band >= 2, // capitals first; lowercase from band 2 (matches the letter stage)
        expected: word,
        hint: `Blend the sounds together: ${letters.join('-')} → ${word}.`,
        sayQ: ['q-buildword'],
        sayA: [`word-${word}`],
      },
    ],
  };
}

export const blendWords = {
  id: 'blend-words',
  title: 'Blending',
  boardKind: 'blendWord',
  bands: [0, 1, 2],
  generate: genBlend,
};

// ── Word Families ───────────────────────────────────────────────────────────
// A rime stays the same (-at); swap the first letter to make a new word. Prompt
// plays a word; the child taps the onset letter that starts it.
export const FAMILIES = [
  { rime: 'at', words: ['cat', 'hat', 'mat', 'sat', 'rat'], band: 0 },
  { rime: 'an', words: ['can', 'pan', 'fan', 'man', 'ran'], band: 0 },
  { rime: 'ig', words: ['pig', 'dig', 'big', 'fig', 'wig'], band: 0 },
  { rime: 'op', words: ['top', 'cop', 'mop', 'hop', 'pop'], band: 1 },
  { rime: 'un', words: ['sun', 'run', 'fun', 'bun'], band: 2 },
];
export const FAMILY_WORDS = [...new Set(FAMILIES.flatMap((f) => f.words))];

export function genWordFamily(band = 0) {
  const fams = FAMILIES.filter((f) => f.band <= band);
  const fam = pick(fams.length ? fams : [FAMILIES[0]]);
  const target = pick(fam.words);
  const onsets = [...new Set(fam.words.map((w) => w[0]))];
  const distractors = shuffle(onsets.filter((o) => o !== target[0])).slice(0, 3);
  const choices = shuffle([target[0], ...distractors]);
  return {
    kind: 'wordFamily',
    word: target,
    rime: fam.rime,
    result: target[0],
    steps: [
      {
        focus: [], targets: ['ans-0'], effects: [], preEffects: [],
        chip: { label: 'Word Families', color: C.amber },
        banner: `The ${'-' + fam.rime} family — which letter starts this word?`,
        prompt: 'Tap the first letter you hear',
        audioPrompt: `word-${target}`,
        rime: fam.rime,
        inputKind: 'choice',
        choices,
        lower: band >= 2,
        expected: target[0],
        hint: `"${target}" starts with ${target[0].toUpperCase()} — it's in the ${'-' + fam.rime} family.`,
        sayQ: [`word-${target}`],
        sayA: [`word-${target}`],
      },
    ],
  };
}

export const wordFamilies = {
  id: 'word-families', title: 'Word Families', boardKind: 'wordFamily', bands: [0, 1, 2], generate: genWordFamily,
};

// ── Digraphs (Tricky Teams) ─────────────────────────────────────────────────
// Two letters that team up to make ONE sound. Reuses the Sound→Letter board
// (choice tiles are the two-letter teams). `phon-<team>` sound clips + example words.
export const DIGRAPHS = [
  { team: 'sh', key: 'phon-sh', sound: '/sh/', word: 'ship' },
  { team: 'ch', key: 'phon-ch', sound: '/ch/', word: 'chip' },
  { team: 'th', key: 'phon-th', sound: '/th/', word: 'thumb' },
  { team: 'ck', key: 'phon-ck', sound: '/k/', word: 'duck' },
];
export const DIGRAPH_WORDS = DIGRAPHS.map((d) => d.word);

export function genDigraph() {
  const target = pick(DIGRAPHS);
  const choices = shuffle(DIGRAPHS.map((d) => d.team));
  return {
    kind: 'soundToLetter', // same board as letter sounds; tiles are 2-letter teams
    letter: target.team,
    word: target.word,
    result: target.team,
    steps: [
      {
        focus: [], targets: ['ans-0'], effects: [], preEffects: [],
        chip: { label: 'Tricky Teams', color: C.purple },
        banner: 'Two letters, one sound — which team did you hear?',
        prompt: 'Tap the letter team you hear',
        audioPrompt: target.key,
        inputKind: 'choice',
        choices,
        expected: target.team,
        hint: `Those two letters say ${target.sound}, like in "${target.word}".`,
        sayQ: ['q-whichteam', target.key],
        sayA: [`word-${target.word}`],
      },
    ],
  };
}

export const digraphTeams = {
  id: 'digraphs', title: 'Tricky Teams', boardKind: 'digraphs', bands: [0], generate: genDigraph,
};

export const PHONICS_TOPICS = [letterSounds, blendWords, wordFamilies, digraphTeams];
