// Reading — English Quest World 4 (Story Harbor). Read-along stations: a short decodable
// story is narrated word by word (StoryReader board highlights each word, karaoke-style,
// with a pause control), then the child answers a question.
//   - First Readers: tap the word you heard (recognition).
//   - Main Idea / Find the Detail / Inference: a spoken wh-question + word choices.
// Stories + answers + distractors all use EXISTING word-<w> clips (zero new word audio);
// only the wh-question prompts (rq-*) are new clips, generated by gen-voice from
// READING_QUESTION_LINES below. See docs/specs/2026-06-14-story-harbor-design.md.
//
// Generators are content-injected: each takes (items, ctx) so the loader can feed a
// course's authored content + band context, mirroring vocab.js. The content arrays below
// are fixtures the topic exports bind for the bundled English course.

const pick = (arr) => arr[Math.floor(Math.random() * arr.length)];
const shuffle = (arr) => {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; }
  return a;
};
const C = { rose: '#F472B6', pink: '#F9A8D4', plum: '#E879F9' };

const clean = (w) => w.toLowerCase().replace(/[^a-z]/g, '');
const toWords = (story) => story.split(/\s+/).map((text) => ({ text, say: `word-${clean(text)}` }));

// ── narrated wh-question prompts (new clips; gen-voice generates these) ──
export const READING_QUESTION_LINES = {
  'rq-main': 'What is the story about?',
  'rq-where-cat': 'Where is the cat?',
  'rq-dog-see': 'What can the dog see?',
  'rq-hen-sit': 'What did the hen sit on?',
  'rq-where-pig': 'Where is the pig?',
  'rq-feel-dog': 'How does the dog feel?',
  'rq-feel-cat': 'How does the cat feel?',
};

// ── First Readers (recognition) ──
export const STORY_ITEMS = [
  { story: 'The cat is on the mat. The cat can nap.', q: 'cat', d: ['mat', 'hat', 'map'] },
  { story: 'The dog can run. We see the dog.', q: 'dog', d: ['pig', 'bug', 'hen'] },
  { story: 'The bug is on the web. The bug is little.', q: 'web', d: ['box', 'net', 'cup'] },
  { story: 'We can see the sun. The sun is hot.', q: 'sun', d: ['bed', 'van', 'jet'] },
  { story: 'The pig is big. The pig sat down.', q: 'pig', d: ['cat', 'dog', 'hen'] },
  { story: 'The hen sat on the egg. The egg is little.', q: 'egg', d: ['box', 'cup', 'mat'] },
];

// `items` is the storyItems array ({ story, q, d } recognition items).
export function genFirstReaders(items, ctx = {}) {
  const item = pick(items);
  const choices = shuffle([item.q, ...item.d]);
  return {
    kind: 'storyReader', word: item.q, result: item.q, story: item.story,
    steps: [{
      focus: [], targets: ['ans-0'], effects: [], preEffects: [],
      chip: { label: 'First Readers', color: C.rose },
      banner: 'Read along, then tap the word you heard',
      prompt: 'Tap the word you heard',
      words: toWords(item.story),
      audioPrompt: `word-${item.q}`,
      inputKind: 'choice', choices, lower: true, expected: item.q,
      hint: `Listen for "${item.q}".`,
      sayQ: [`word-${item.q}`], sayA: [`word-${item.q}`],
    }],
  };
}

// ── comprehension (Main Idea / Find the Detail / Inference) ──
// item = { story, q (clip key), text (displayed question), a (answer), d (distractors) }.
// Curried so a registry entry can bind label+color once: comprehension('Main Idea', C.pink)
// returns a content-injected (items, ctx) => problem generator.
export function comprehension(label, color) {
  return (items, ctx = {}) => {
    const it = pick(items);
    const choices = shuffle([it.a, ...it.d]);
    return {
      kind: 'storyReader', word: it.a, result: it.a, story: it.story,
      steps: [{
        focus: [], targets: ['ans-0'], effects: [], preEffects: [],
        chip: { label, color },
        banner: 'Read along, then answer',
        prompt: it.text,
        words: toWords(it.story),
        audioPrompt: it.q,
        inputKind: 'choice', choices, lower: true, expected: it.a,
        hint: `The answer is "${it.a}".`,
        sayQ: [it.q], sayA: [`word-${it.a}`],
      }],
    };
  };
}

export const MAIN_IDEA_ITEMS = [
  { story: 'The cat sat on the mat. The cat can nap. The cat is little.', q: 'rq-main', text: 'What is the story about?', a: 'cat', d: ['dog', 'sun', 'bus'] },
  { story: 'We can see the sun. The sun is hot. The sun is big.', q: 'rq-main', text: 'What is the story about?', a: 'sun', d: ['web', 'hen', 'jet'] },
  { story: 'The dog can run. The dog can dig. The dog is fast.', q: 'rq-main', text: 'What is the story about?', a: 'dog', d: ['pig', 'egg', 'cup'] },
  { story: 'The bug is on the web. The bug is little. The bug can sit.', q: 'rq-main', text: 'What is the story about?', a: 'bug', d: ['sun', 'van', 'mat'] },
];

export const DETAIL_ITEMS = [
  { story: 'The cat is on the mat. The cat is big.', q: 'rq-where-cat', text: 'Where is the cat?', a: 'mat', d: ['box', 'bed', 'web'] },
  { story: 'The dog can run. The dog can see the sun.', q: 'rq-dog-see', text: 'What can the dog see?', a: 'sun', d: ['web', 'egg', 'net'] },
  { story: 'The hen sat on the egg. The egg is little.', q: 'rq-hen-sit', text: 'What did the hen sit on?', a: 'egg', d: ['mat', 'box', 'cup'] },
  { story: 'The pig is in the box. The pig is big.', q: 'rq-where-pig', text: 'Where is the pig?', a: 'box', d: ['mat', 'bed', 'web'] },
];

export const INFERENCE_ITEMS = [
  { story: 'The dog can run and jump. The dog can dig.', q: 'rq-feel-dog', text: 'How does the dog feel?', a: 'happy', d: ['sad', 'mad'] },
  { story: 'The dog is wet. The dog is cold.', q: 'rq-feel-dog', text: 'How does the dog feel?', a: 'sad', d: ['glad', 'happy'] },
  { story: 'The cat sat in the sun. The cat can nap.', q: 'rq-feel-cat', text: 'How does the cat feel?', a: 'glad', d: ['sad', 'mad'] },
];

export const firstReaders = { id: 'first-readers', title: 'First Readers', boardKind: 'firstReader', bands: [0], generate: (band) => genFirstReaders(STORY_ITEMS, { band }) };
export const mainIdea = { id: 'main-idea', title: 'Main Idea', boardKind: 'mainIdea', bands: [0], generate: (band) => comprehension('Main Idea', C.pink)(MAIN_IDEA_ITEMS, { band }) };
export const findDetail = { id: 'find-detail', title: 'Find the Detail', boardKind: 'findDetail', bands: [0], generate: (band) => comprehension('Find the Detail', C.pink)(DETAIL_ITEMS, { band }) };
export const inference = { id: 'inference', title: 'Read Between the Lines', boardKind: 'inference', bands: [0], generate: (band) => comprehension('Inference', C.plum)(INFERENCE_ITEMS, { band }) };

export const READING_TOPICS = [firstReaders, mainIdea, findDetail, inference];
